
--권한주기
GRANT CREATE VIEW TO SCOTT;

GRANT CREATE SYNONYM TO SCOTT;

--------------------------------------
CREATE USER ORCLSTUDY
IDENTIFIED BY ORCL;

GRANT RESOURCE, CONNECT TO ORCLSTUDY;

GRANT SELECT ON SCOTT.EMP TO ORCLSTUDY;

GRANT SELECT,INSERT ON SCOTT.DEPT TO ORCLSTUDY;

---------------------------------------
CREATE ROLE ROLE_NAME;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM TO ROLE_NAME;

GRANT ROLE_NAME TO ORCLSTUDY;

SELECT * FROM USER_SYS_PRIVS;
SELECT * FROM USER_ROLE_PRIVS;

-----------------------------------------

--1. MADANG 사용자 만들기
CREATE USER MADANG
IDENTIFIED BY MADANG;

--2. BOOKS테이블 만들기
GRANT CREATE SESSION TO MADANG;

GRANT RESOURCE, CONNECT TO MADANG;


---------------------------------------------- 1121M----
CREATE USER MOVIE
IDENTIFIED BY MOVIE;

GRANT RESOURCE, CONNECT TO MOVIE;

------------------------------------------------

CREATE USER SCOT
IDENTIFIED BY SCOT;

GRANT RESOURCE, CONNECT TO SCOT;
